development:
  adapter: postgresql
  database: rehactive_development
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost

test:
  adapter: postgresql
  database: rehactive_test
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost

production:
  adapter: postgresql
  database: rehactive_production
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
